name: Advanced Usage

on: push

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: create file list
        id: files_list
        run: |
          mkdir output  # create output dir
          echo "files=$(printf '"%s" ' *.md)" > $GITHUB_OUTPUT
      - uses: docker://danteev/texlive 
      #uses: docker://pandoc/latex:2.9
        with:
          args: 
          >-  # allows you to break string into multiple lines
          --template=din5008.latex 
          --output=output/result.pdf ${{ steps.files_list.outputs.files }}
      - uses: actions/upload-artifact@v3
        with:
          name: output
          path: output
